### ISSUE TITLE
 [4wd1] 181028 大作业 | 「模范家长工具箱」线上会议

### ISSUE THREAD

**Issue by tanchangde** [tanchangde/tanchangde.github.io#1]
## 时间地点

- 时间：今日 20:00
- 方式： Zoom 线上会议
- 会议入口：https://zoom.us/j/8911284593

## 议程及目的

- 约束自我，达成到作业轮廓共识
- 抛出关于大作业名名称的想法
  - 性感、击中自主心智
- 达成分工共识
- 达成里程碑共识
  - 如输出节点，输出内容

## 会议记录

视频/录音链接 (百度云盘):

- 链接:https://pan.baidu.com/s/10MfZ-U2Qf6fyjaTTi_GNTg  
- 密码:a6tt

## 协作要求

- 会议结束后，尽早以 Comment 方式在本 Issue 提交个人[石墨账号](https://shimo.im/)，以便共同协作
- 42 小时内，提交会议复盘到本 Issue，便于后续回溯（可以是要点纪要、也可以是有益于项目推进的想法）

## 会前热身

参加会议前，建议刷一刷

- [结业大作业分享交流会复盘-浩涛教练的分享](https://github.com/AIHackers/IA002/issues/96#issuecomment-433052134)，单看 Keynote 没有感觉的可结合[视频回放](https://zoom.us/recording/play/tStvLPxhpduaeHA-NotS-MSxUNPFTmcaKpYtBKKwjmGM2EWSmRZm-DKAxT9I1c73?autoplay=true&startTime=1540466487000)，观看对应时段，建立对大作业的全局认识
- [体制内工作人员职业生涯分析报告](https://github.com/linhaotao/AIhackers001BP-NationalstaffsCareerRPT)仓库，感受输出迭代节奏；
- [智能时代应对指南](https://pan.baidu.com/s/1XgbQNxVNDuOuEOIpAIMGOg)，感受输出

**Comment by zhujiuye2018** [comment]
石墨文档  账号   朱九爷2018    13685858253
